project:
  type: website

website:
  navbar:
    background: "#26155c"
    left: 
      - index.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jabirG
      - icon: twitter
        href: https://twitter.com/data_Jabs

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css



